pipeline {
  agent {
    docker {
      image 'maven:3.6.2-jdk-12'
    }

  }
  stages {
    stage('Test') {
      steps {
        echo 'Unit Test Account Service'
        dir(path: 'accounts') {
          sh 'mvn clean test'
        }
      }
    }
    stage('Package') {
      steps {
        echo 'Package Account Service'
        dir(path: 'accounts') {
          sh 'mvn package -Dmaven.test.skip=true'
        }
      }
    }
    stage('Deliver') {
      steps {
        echo 'Deliver Account Service'
        dir(path: 'accounts') {
          script {
            docker.build registry
          }
        }
      }
    }
    stage('Dev Deployment') {
      when {
        branch 'develop'
      }
      steps {
        echo 'Deploy Account Service on develop environment'
        dir(path: 'accounts') {
          echo 'TODO deployment on k8s'
        }
      }
    }
    stage('Integration Test') {
      when {
        branch 'develop'
      }
      steps {
        echo 'Run Integration Test Suite'
        dir(path: 'accounts') {
          echo 'TODO enable integration test suite'
        }
      }
    }
    stage('Prod Deployment') {
      when {
        branch 'master'
      }
      steps {
        echo 'Deploy Account Service on production environment'
        input message: 'Deploying Account Service on Production? (Click "Proceed" to continue)'
        dir(path: 'accounts') {
          echo 'TODO deployment on k8s'
        }
      }
    }
  }
  environment {
    registry = 'wpnpeiris/american-orange-cadillac-accounts'
  }
}

